### ISSUE TITLE
Reliance on TOS

### ISSUE THREAD

**Issue by vinz6751** [th-otto/pcmake#3]
Thanks for this pcmake tool, I use it a lot and really love it!
I'm using it on the Foenix A2560 and there it crashes when execute from the flash though. I found that it's because of the malloc implementation borrowed from the MiNTlib, which tries to do things based on TOS version which don't work on the Foenix.
To fix it, I rebuild pcmake using libcmini and it appears to work (though I didn't build massive projects), but now the '\n' are not translated to '\r\n' anymore when outputting messages to the console. I replaced \n with \r\n everywhere I could but it seems not enough. "usage" displays nicely
Before I go further down that rabbit hole, I'd like to know your opinion about that memory issue please

**Comment by th-otto** [comment]
> To fix it, I rebuild pcmake using libcmini and it appears to work

Thats strange, because libcmini uses the same malloc implementation. But the TOS version checks can safely be removed, they are only needed for ACCs on Single-TOS, to prevent the Malloc()ed blocks being assigned to the desktop.

Maybe you can try with the fixed version? (just removed those checks)

>but now the '\n' are not translated to '\r\n' anymore when outputting messages to the console

Yes, thats a problem of libcmini on single-tos. Of course using libcmini makes sense when you put in the flash, to reduce its size.

**Comment by vinz6751** [comment]
Thank you for the response: I tried with the fix version:
I got errors because "#include <mint/arch/nf_ops.h>" fails (the file doesn't exist)
If I comment that out, it compiles ok...

I saw https://github.com/freemint/libcmini/issues/102 so I recompiled libcmini with -DSTDIO_MAP_NEWLINE and now it's all good.

I attach a zipped patch (but not something you want to merge because I deleted stuff!) in case you're interested.
[pcmake-with-libcmini.zip](https://github.com/th-otto/pcmake/files/13227729/pcmake-with-libcmini.zip)

The utility is 150+KB with mintlib, 63K (not even half) with libcmini.
Thanks again for the help :)

**Comment by th-otto** [comment]
> I got errors because "#include <mint/arch/nf_ops.h>" fails (the file doesn't exist)

Hm, libcmini should have that too: https://github.com/freemint/libcmini/tree/master/include/mint/arch. But the include can be removed from malloc.c, along with 2 other includes, that are now no longer needed. It is however used in other places; i need that when running pcmake in a headless aranym environment, so that the progress messages are printed to the host instead.

> The utility is 150+KB with mintlib, 63K (not even half) with libcmini.

Compiled with Pure-C, it's even smaller (~43k). But i don't know whether the pcstdlib has other problems in your environment.
